---
exclude_paths:
- bower_components/
- js/vendor/
- languages/
- node_modules/
- tests/
- vendor/
- "**.css"
- "*.min.css"
- "*.min.js"
- "js/script.js"
- ".sass-cache/"

prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.scss-lint-r-2.x.yml"
    path: ".scss-lint.yml"
  - url: "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/phpcs-themes.xml"
    path: "phpcs.xml"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintrc"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.eslintignore"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/.mdlrc"
  - "https://raw.githubusercontent.com/bu-ist/coding-standards/master/code-climate-rule-sets/markdown.rb"

engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
    exclude_paths:
      - "Gruntfile.js"
  eslint:
    enabled: true
    channel: eslint-3
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: "phpcs.xml"
      ignore_warnings: false
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: php
      rulesets: codesize,naming,unusedcode
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.json"
  - "**.md"
  - "**.php"
  - "**.scss"
